version: "3.7"

services:
  mongodb:
    image: mongo
    build:
      context: mongo
      dockerfile: Dockerfile
    container_name: mongodb
    hostname: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=master
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=user
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongo-data:/data/db
    ports:
      - "9511:27017"
    command: mongod --logpath=/dev/null
    networks:
      - default
      - vxds-dev-tools

  mongo-express:
    image: mongo-express
    build:
      context: mongo-express
      dockerfile: Dockerfile
    container_name: mongo-express
    hostname: mongo-express
    restart: always
    ports:
      - "9611:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    entrypoint: ./dockerize -wait http://mongodb:27017 -timeout 120s
    command: node /node_modules/mongo-express/app.js
    networks:
      - default
      - vxds-dev-tools
    depends_on:
      - mongodb

networks:
  default:
    driver: bridge
  vxds-dev-tools:
    external: true

volumes:
  mongo-data:
