matrix:
  include:
    - name: "Docker Containers"
      language: minimal
      services:
        - docker
      before_install: cd Containers
      install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      script:
        - docker-compose -f camunda-server/docker-compose.yml build --no-cache
        - docker-compose -f mssql/docker-compose.yml build --no-cache
        - docker-compose -f mongodb/docker-compose.yml build --no-cache
    - name: "Camunda Server"
      language: java
      jdk:
      - openjdk12
      sudo: false
      before_install: cd ExtTools/CamundaServer
      install: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script: mvn test -B
    - name: "Development Tools"
      language: csharp
      mono: none
      dotnet: 2.2
      dist: xenial
      sudo: required
      global:
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
        - DOTNET_CLI_TELEMETRY_OPTOUT=1
      before_install:
        - nvm install 12
        - nvm use 12
        - cd DevTools
      install:
        - npm install -C UnifiedPortal/Static
        - dotnet restore
      script:
        - dotnet build
