version: "3.7"

services:
  simple-note-service.deployments.upgrade:
    image: vxds-dev-tools
    entrypoint: /scripts/dockerize -wait http://camunda-server:9221 -timeout 60s
    command: dotnet run --project Modules/SimpleNoteService/Camunda/Workflows/Workflows.csproj --launch-profile "Docker + Local" upgrade
    networks:
      - vxds-dev-tools

  simple-note-service.deployments.rollback:
    image: vxds-dev-tools
    entrypoint: /scripts/dockerize -wait http://camunda-server:9221 -timeout 60s
    command: dotnet run --project Modules/SimpleNoteService/Camunda/Workflows/Workflows.csproj --launch-profile "Docker + Local" rollback
    networks:
      - vxds-dev-tools

  simple-note-service.deployments.downgrade:
    image: vxds-dev-tools
    entrypoint: /scripts/dockerize -wait http://camunda-server:9221 -timeout 60s
    command: dotnet run --project Modules/SimpleNoteService/Camunda/Workflows/Workflows.csproj --launch-profile "Docker + Local" downgrade
    networks:
      - vxds-dev-tools

networks:
  vxds-dev-tools:
    external: true
