version: "3.7"

services:
  simple-note-service.workers:
    image: vxds-dev-tools
    entrypoint: /scripts/dockerize -wait http://camunda-server:9221 -timeout 60s
    command: dotnet run --project Modules/SimpleNoteService/Camunda/Workers/Workers.csproj --launch-profile "Docker + Local"
    networks:
      - vxds-dev-tools

networks:
  vxds-dev-tools:
    external: true
