version: "3.7"

services:
  sql-server:
    # Available: mcr.microsoft.com/mssql/server:2019-latest
    image: microsoft/mssql-server-linux
    container_name: sql-server
    hostname: sql-server
    restart: always
    environment:
      - SA_PASSWORD=<2019!Pass>
      - ACCEPT_EULA=Y
    ports:
      - "9501:1433"
    networks:
      - vxds-dev-tools
    volumes:
      - sql-server-data:/var/opt/mssql

networks:
  vxds-dev-tools:
    external: true

volumes:
  sql-server-data:
