version: "3.7"

services:
  sql-server:
    image: microsoft/mssql-server-linux
    container_name: sql-server
    hostname: sql-server
    restart: always
    environment:
      - SA_PASSWORD=<2019!Pass>
      - ACCEPT_EULA=Y
    ports:
      - "9501:1433"
    volumes:
      - sql-server-data:/var/opt/mssql

volumes:
  sql-server-data:
