version: "3.7"

services:
  postgres-camunda:
    image: postgres
    container_name: postgres-camunda
    hostname: postgres-camunda
    restart: always
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=<2019!Pass>
      - POSTGRES_DB=master
    ports:
      - "9502:5432"
    volumes:
      - postgres-camunda-data:/var/lib/postgresql/data

  camunda-server:
    image: camunda-server
    depends_on:
      - postgres-camunda
    build:
      context: ../../ExtTools/CamundaServer
      dockerfile: ../../Containers/camunda-server/Dockerfile
    container_name: camunda-server
    hostname: camunda-server
    restart: always
    ports:
      - "9201:9201"
    networks:
      - default
    command: java -jar -Dspring.datasource.url=jdbc:postgresql://postgres-camunda:5432/master CamundaServer.jar

volumes:
  postgres-camunda-data: