spring.datasource:
  username: sa
  password: <2019!Pass>
  url: jdbc:postgresql://localhost:5432/master
camunda.bpm:
  admin-user:
    id: vxdesign
    password: vxdesign
    firstName: Roman
    lastName: Mashenkin
    email: xromash@vxdesign.store
  database:
    type: postgres
    schema-update: true
  rest-auth:
    required: true
  filter:
    create: All tasks
server.port: 9221